services:
  # 1. Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      - TZ=${TZ:-UTC}
      - NEXT_PUBLIC_API_URL=http://192.168.8.170:8080
      - NEXT_PUBLIC_WHEP_URL=http://192.168.8.170:8888
      - NEXT_PUBLIC_HLS_URL=http://192.168.8.170:8887
    depends_on:
      - backend
    networks:
      - cam_net
    restart: unless-stopped
    user: "appuser"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true

  # 2. Backend (Go)
  backend:
    build:
      context: ./backend-go # <--- Changed context
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=${TZ:-UTC}
    secrets:
      - db_url_secret
      - jwt_secret_key
      - db_password # <--- Ensure this is listed here!
    depends_on:
      db:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - cam_net
    restart: always
    volumes:
      - ./recordings:/recordings
      - /var/run/docker.sock:/var/run/docker.sock

  # 3. Database
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - TZ=${TZ:-UTC}
      - POSTGRES_USER=admin
      - POSTGRES_DB=cameradb
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cam_net
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cameradb"]
      interval: 5s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true

  # 4. Media Server
  mediamtx:
    image: bluenviron/mediamtx:1-ffmpeg
    restart: always
    ports:
      - "8888:8888"
      - "8554:8554"
      - "1935:1935"
      - "8189:8189/udp"
      - "8887:8887"
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings # <--- CHANGED
    networks:
      - cam_net
    security_opt:
      - no-new-privileges:true

  # 5. AI Detector
  ai-detector:
    build:
      context: ./ai-detector
    restart: always
    depends_on:
      - backend
      - mediamtx
    volumes:
      - ./ai-detector:/app
    networks:
      - cam_net

networks:
  cam_net:
    driver: bridge

volumes:
  db_data:

secrets:
  db_password:
    file: ./db_password.txt
  jwt_secret_key:
    file: ./secret_key.txt
  db_url_secret:
    file: ./db_url.txt
