services:
  # 1. Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_WHEP_URL=http://localhost:8888
    depends_on:
      - backend
    networks:
      - cam_net
    restart: unless-stopped
    user: "appuser" # <-- 1. Run as the non-root user
    read_only: true # <-- 2. Make filesystem read-only
    tmpfs: # <-- 3. Mount a temporary filesystem for Next.js to write to
      - /tmp
    security_opt: # <-- 4. Prevent privilege escalation
      - no-new-privileges:true

  # 2. Backend (FastAPI)
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - db_url_secret
      - jwt_secret_key
    depends_on:
      db:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - cam_net
    restart: always
    user: "appuser" # <-- 1. Run as the non-root user
    security_opt: # <-- 4. Prevent privilege escalation
      - no-new-privileges:true

  # 3. Database (PostgreSQL)
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=cameradb
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cam_net
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cameradb"]
      interval: 5s
      timeout: 5s
      retries: 5
    security_opt: # <-- 4. Prevent privilege escalation
      - no-new-privileges:true

  # 4. Media Server (mediamtx)
  mediamtx:
    image: bluenviron/mediamtx:1-ffmpeg
    restart: always
    ports:
      - "8888:8888" # WHEP/WHIP (WebRTC)
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP
      - "8189:8189/udp"
      - "8887:8887" # HLS
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    networks:
      - cam_net
    security_opt: # <-- 4. Prevent privilege escalation
      - no-new-privileges:true

networks:
  cam_net:
    driver: bridge

volumes:
  db_data:

secrets:
  db_password:
    file: ./db_password.txt
  jwt_secret_key:
    file: ./secret_key.txt
  db_url_secret:
    file: ./db_url.txt
